### ISSUE TITLE
Feature request: Custom add time length when entering pomodoro

### ISSUE THREAD

**Issue by mzwlevi** [denvey/logseq-pomodoro-technique#1]
This plugin was awesome, thank you for your work!
Do you have the plan with custom add time length when entering pomodoro?
Just like roam:
![Screen Shot 2022-09-07 at 00 19 46](https://user-images.githubusercontent.com/78029539/188686131-a06e5e95-05da-4775-b658-016f2deea81e.png)

**Comment by mzwlevi** [comment]
> This plugin was awesome, thank you for your work! Do you have the plan with custom add time length when entering pomodoro? Just like roam: ![Screen Shot 2022-09-07 at 00 19 46](https://user-images.githubusercontent.com/78029539/188686131-a06e5e95-05da-4775-b658-016f2deea81e.png)

This will be useful when we need to use different time length in one place.

**Comment by mzwlevi** [comment]
![Screen Shot 2022-09-07 at 00 25 34](https://user-images.githubusercontent.com/78029539/188687300-4a86baff-2a35-4cd6-8e9a-e1f84d0ab816.png)

**Comment by denvey** [comment]
Thank you very much for your suggsetion，I'll think about it in the next version.
