### ISSUE TITLE
UI Not updating

### ISSUE THREAD

**Issue by mbifulco** [denvey/logseq-pomodoro-technique#7]
I use a 5 minute pomodoro timer each for a journaling activity. When I add a timer to my daily journal with `/pmo` , I see a start button:

<img width="137" alt="image" src="https://github.com/denvey/logseq-pomodoro-technique/assets/1844496/fe84a994-dddf-4356-b14b-f421632d2a17">

When I click start, the button turns red and shows 5:00, but it doesn't change at all until the 5 minutes have passed
<img width="200" alt="image" src="https://github.com/denvey/logseq-pomodoro-technique/assets/1844496/d2dd0a74-a067-42dc-a978-1ce51d54c1bf">

Once 5 minutes have passed, it changes to the completed state:
<img width="117" alt="image" src="https://github.com/denvey/logseq-pomodoro-technique/assets/1844496/f5873745-6383-436a-bf46-fc01c48f021c">

Is that the expected behavior? If not, am I doing something wrong?

**Comment by denvey** [comment]
No,unexpected effects, due to changes in the logseq API during the upgrade, have been fixed and will be released today.

**Comment by denvey** [comment]
Thanks @eagleon 
#8

**Comment by denvey** [comment]
#8 
Thanks @eagleon
